import './globals.css'
import Navbar from '@/Components/navbar'
import Footer from '@/Components/footer'



export const metadata = {
  title: 'Soulthreads',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"bg-[#ffe7e7]"}>
        <Navbar/>
        {children}
        <Footer/>
    
        </body>
    </html>
  )
}
